name: Deploy infotech

on:
  push:
    branches:
      - main
      - staging

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SERVER_SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to Staging
        if: github.ref_name == 'staging'
        run: |
          ssh ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} "
            cd /var/www/staging.zalgoinfotech.in/Zalgo_infotech &&
            git fetch origin &&
            git reset --hard origin/staging &&
            git clean -fd &&
            composer install &&
            php artisan migrate --force &&
            php artisan optimize
          "

      - name: Deploy to Production
        if: github.ref_name == 'main'
        run: |
          ssh ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} "
            cd /var/www/zalgoinfotech.com &&
            git fetch origin &&
            git reset --hard origin/main &&
            git clean -fd &&
            composer install --no-dev --optimize-autoloader &&
            php artisan migrate --force &&
            php artisan optimize
          "